### ISSUE TITLE
Broken link in the smart contract

### ISSUE THREAD

**Issue by n1c01a5** [DemocracyEarth/ubi#75]
The link for `ERC20BurnableUpgradeable.sol` https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/token/ERC20/ERC20BurnableUpgradeable.sol is broken.

**Comment by santisiri** [comment]
Where did you find this broken link exactly?

**Comment by n1c01a5** [comment]
Here https://github.com/DemocracyEarth/ubi/blob/ce2f76372ed209e4887f869db082b9f173799378/contracts/UBI.sol#L5

**Comment by santisiri** [comment]
Not anymore in the version in `master` since all ERC20 functionality was brought upfront straight to the contract for gas optimization. `burn()` is now present in line 227 for instance: https://github.com/DemocracyEarth/ubi/blob/ce2f76372ed209e4887f869db082b9f173799378/contracts/UBI.sol#L227

I will remove that comment. Thanks @n1c01a5
